### ISSUE TITLE
Names of files are not accepted in Arduino IDE

### ISSUE THREAD

**Issue by pe1mew** [gonzalocasas/arduino-mkr-wan-1300#1]
When opening the example files the Arduino IDE complains that filenames may not start with a number.
After renaming them the files can be opened in Arduino IDE.

**Comment by gonzalocasas** [comment]
@pe1mew which version/OS of arduino IDE do you have? I tested it on Mac's latest IDE and it worked, I can rename anyway but I want to understand where it fails.

**Comment by pe1mew** [comment]
It was Arduino 1.6.4 on Windows 7. 
I am not complaining. It is something that can happen on different OS and just needs to be mentioned.

**Comment by gonzalocasas** [comment]
@pe1mew ah, yep, that's the thing. It's only since 1.8.4 that this is allowed:

![image](https://user-images.githubusercontent.com/933277/35269780-4f49e9d4-002d-11e8-8b28-cbfa7218e65e.png)

> I am not complaining.

No worries, complaining is good.

Regarding the issue, I think it's good to have numbered sketches because it makes it very clear for people new to everything where the have to start. Maybe adding a prefix to all? `mkr_wan_01_get_deveui` and `mkr_wan_02_hello_world`?

**Comment by pe1mew** [comment]
The use of sensible names is mandatory to keep things organized. A prefix seems to be the appropriate solution.

**Comment by gonzalocasas** [comment]
Fixed in 4e7b2e69da15cc619e9696adcaa6fa81393c45cc
